apiVersion: v1
kind: ConfigMap
metadata:
  name: seldon-deploy-config
data:
  prometheusSeldonUrl: {{ .Values.prometheus.seldon.url }}
{{- if .Values.prometheus.seldon.resourceMetricsUrl }}
  prometheusSeldonResourceUrl: {{ .Values.prometheus.seldon.resourceMetricsUrl }}
{{- else }}
  prometheusSeldonResourceUrl: {{ .Values.prometheus.seldon.url }}
{{- end }}
  prometheusKnativeUrl: {{ .Values.prometheus.knative.url }}
  prometheusNamespaceMetricName: {{ .Values.prometheus.seldon.namespaceMetricName }}
  prometheusServiceMetricName: {{ .Values.prometheus.seldon.serviceMetricName }}
  elasticsearchUrl: {{ .Values.elasticsearch.url }}
  argocdEnabled: {{ .Values.gitops.argocd.enabled | quote}}
  skipVerifyGit: '{{ .Values.gitops.git.skipVerifyGit }}'
  skipVerifyHttpCalls: '{{ .Values.skipVerifyHttpCalls }}'
  seldonIngressService: {{ .Values.ingressGateway.seldonIngressService }}
  ingressNamespace: {{ .Values.ingressGateway.ingressNamespace }}
  kfServingIngressService: {{ .Values.ingressGateway.kfServingIngressService }}
  kfServingCurlForm: {{ .Values.kfserving.curlForm | quote }}
  kfServingRequestForm: {{ .Values.kfserving.requestForm | quote }}
  kfServingExplainForm: {{ .Values.kfserving.explainForm | quote }}
  kfServingProtocol: {{ .Values.kfserving.protocol | quote }}
  seldonCurlForm: {{ .Values.seldon.curlForm | quote }}
  seldonTensorflowCurlForm: {{ .Values.seldon.tensorFlowCurlForm | quote }}
  seldonKFServingV2CurlForm: {{ .Values.seldon.kfservingV2CurlForm | quote }}  
  seldonRequestForm: {{ .Values.seldon.seldonRequestForm | quote }}
  seldonTensorflowRequestForm: {{ .Values.seldon.tensorflowRequestForm | quote }}
  seldonV2RequestForm: {{ .Values.seldon.v2RequestForm | quote }}
  seldonExplainForm: {{ .Values.seldon.explainForm | quote }}
  seldonProtocol: {{ .Values.seldon.protocol | quote }}
