artifactory:
  artifactory:
    image:
      registry: releases-docker.jfrog.io
      repository: jfrog/artifactory-jcr
    resources: 
      requests:
        memory: "1Gi"
        cpu: "500m"
      limits:
        memory: "4Gi"
        cpu: "1"
    javaOpts: 
      xms: "1g"
      xmx: "3g"
      other: ""
    persistence: 
      mountPath: "/var/opt/jfrog/artifactory"
      enabled: false
      accesMode: ReadWriteOnce
      size: 50Gi
  installer:
    platform: jcr-helm
  installerInfo: '{"productId": "Helm_artifactory-jcr/{{ .Chart.Version }}", "features": [ { "featureId": "Platform/{{ default "kubernetes" .Values.installer.platform }}"}]}'
  nginx:
    enabled: false
    tlsSecretName: ""
    service:
      type: ClusterIP
  ingress:
    enabled: false
    tls:
  postgresql:
    enabled: false

  databaseUpgradeReady: "yes"
  jfconnect:
    enabled: false
  database: 
    type: postgresql
    driver: org.postgresql.Driver
    # # # url: 'jdbc:postgresql://192.168.109.128:5432/artifactory' #local DB
    url: 'jdbc:postgresql://dbms.fredgentech.net:5432/artifactory'
    # user: 'databaseadmin'
    # password: 'aWdka2R6a2FzdHl3ZXFpdXdzCg==' 
    secrets: 
     user:
       name: "artifactory-database"
       key: "user"
     password:
       name: "artifactory-database"
       key: "password"
    #  url: 
    #    name: "artifactory-database"
    #    key: "db-url"
postgresql:
    enabled: false
router:
  image:
    tag: 7.56.0
logger:
  image:
    tag: 8.7.1049
initContainerImage: releases-docker.jfrog.io/ubi8/ubi-minimal:8.7.1049