
# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: config-istio
#   namespace: knative-serving
# data:
#   gateway.istio-system.cluster-local-gateway: cluster-local-gateway.istio-system.svc.cluster.local
#   #gateway.kubeflow.kubeflow-gateway: istio-ingressgateway.istio-system.svc.cluster.local

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: config-deployment
  namespace: knative-serving
data:
  progressDeadline: 600s


---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-domain
  namespace: knative-serving
data:
  knative.fredgentech.net: ""