{{- if and .Values.gitops.git.user .Values.gitops.argocd.enabled -}}
#might later remove git secret and use argocd secret instead
#see https://github.com/argoproj/argo-cd/issues/1342
apiVersion: v1
kind: Secret
metadata:
  name: git-{{ include "seldon-deploy.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "seldon-deploy.name" . }}
    helm.sh/chart: {{ include "seldon-deploy.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  username: {{ .Values.gitops.git.user | toString | b64enc | quote }}
  token: {{ .Values.gitops.git.token | toString | b64enc | quote }}
  email: {{ .Values.gitops.git.email | toString | b64enc | quote }}
{{- end -}}
