{{- if .Values.gitops.git.webhook.service.create -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "seldon-deploy.fullname" . }}-webhook
  labels:
    app.kubernetes.io/name: {{ include "seldon-deploy.name" . }}
    helm.sh/chart: {{ include "seldon-deploy.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  {{- if .Values.gitops.git.webhook.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
  {{ toYaml .Values.gitops.git.webhook.service.loadBalancerSourceRanges | indent 4 }}
  {{- end }}
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: webhook
      protocol: TCP
      name: webhook
  selector:
    app.kubernetes.io/name: {{ include "seldon-deploy.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end -}}