apiVersion: v1
kind: Namespace
metadata:
  name: keycloak
spec: {}
status: {}
--- 
apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
spec: {}
status: {}
--- 
apiVersion: v1
kind: Namespace
metadata:
  name: artifactory
spec: {}
status: {}
--- 
apiVersion: v1
kind: Namespace
metadata:
  name: tracing
spec: {}
status: {}

--- 
apiVersion: v1
kind: Namespace
metadata:
  name: neuvector
spec: {}
status: {}

--- 
apiVersion: v1
kind: Namespace
metadata:
  name: knative-serving
spec: {}
status: {}

--- 
apiVersion: v1
kind: Namespace
metadata:
  name: knative-eventing
spec: {}
status: {}

--- 
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
spec: {}
status: {}

--- 
apiVersion: v1
kind: Namespace
metadata:
  name: jupyterhub
spec: {}
status: {}

--- 
apiVersion: v1
kind: Namespace
metadata:
  name: airflow
spec: {}
status: {}
--- 
apiVersion: v1
kind: Namespace
metadata:
  name: seldon-system
spec: {}
status: {}

--- 
apiVersion: v1
kind: Namespace
metadata:
  name: gitlab
spec: {}
status: {}

--- 
apiVersion: v1
kind: Namespace
metadata:
  name: seldon
spec: {}
status: {}

--- 
apiVersion: v1
kind: Namespace
metadata:
  name: seldon-logs
spec: {}
status: {}

---
apiVersion: v1
kind: Namespace
metadata:
  name: sonarqube
spec: {}
status: {}

---
apiVersion: v1
kind: Namespace
metadata:
  name: kyverno
spec: {}
status: {}