apiVersion: v1
data:
    password: ENC[AES256_GCM,data:I7ljzQo8hPIruH2vLo2TJOHwt7U5q3H/EXMCAR3mMLsGY9fDH0Lk7w==,iv:Wt/mHaO7vb/QKPkGiiTq3YMrF8+JYwBQqAbj7qZDXWk=,tag:WFCtszAAR0Mg8fN65Owb0w==,type:str]
kind: Secret
metadata:
    name: sonarqube-database
    namespace: sonarqube
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17h3ge2vqnqkeemusg3zhmaxq5m0ttf6jkyjeam4a2vnxaaxq4das5wynws
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5NS9rY2dTWFFqZEtyaHRI
            WXUxS25HRWQzMEZ5UmRTV1N3TkIwbHQrYWhFClFqS2VqblpRMDFZYkRKOElDckhN
            U0VTby90ekVtU28yUmlIZEtMZXZGcU0KLS0tIDY0RjNDTUpQOXNHaFJQMGRZQzRt
            c3VqYXhWcE1KeDJtSmJnZzcwL1BGWTQK5CxqiStHE2mCJiOCKVHC/d/Wy/sz9q8S
            pi+5UFwDGtm0CZE20vt3uUmalruXFtuPc5LZyAKcxDnLSX5KMHveoQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-02T18:20:43Z"
    mac: ENC[AES256_GCM,data:fJ+YtQQUCM32ibfw1pDtqqa51fAzp3JVYYAflhUqpLVwtRLubtWmlQMb3CM1cqXvxfcc22txgSQGZK4CaC/KuBjyccFEwxRPsc/1O4mE5Cge46d/WI3d3dq0twqvb80Vc3x0Pr0O6IvbvhVqlTkUHTl+Z5AEqv/zdYMGnpUHjCE=,iv:SUf5xHdtisiLct59Cg45j9pq8wPSLDqI14wvIOaGV2o=,tag:/6IWBcH1bZ29T6Yi+2kX6A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
