apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jaeger
  namespace: argocd
spec:
  project: default
  source:
    repoURL:  https://github.com/asongent/stack.git
    targetRevision: HEAD
    path: jaeger
    helm:
      valueFiles:
      - values.yaml
  destination:
    namespace: tracing
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
