apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: knative-serving
  namespace: argocd
spec:
  project: default
  source:
    repoURL:  https://github.com/asongent/stack.git
    targetRevision: HEAD
    path: knative-serving
    kustomize:
      version: v4.5.7
  destination: 
    namespace: knative-serving
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true