apiVersion: v1
data:
    password: ENC[AES256_GCM,data:bMh+26upSnshfWym+ShaMB+EFbZ1/mKxxfu4jpuWmKEs9rkSMqkRXQ==,iv:JK5I31Cyt/UfqcptM9lj8sn4lNkU8dX2zr4yWJ1cfmY=,tag:WYNj2q15uoJHHuEEATUIhg==,type:str]
    user: ENC[AES256_GCM,data:xJA9bTzwzl+Gn/Ov/vWBbi41RtA=,iv:RdicuGgehrF9KT5QvSbg5I55E6kn/+5qxkjxlg7e1eA=,tag:ysHEyqFQHC05/OXf9WPIyA==,type:str]
kind: Secret
metadata:
    name: artifactory-database
    namespace: artifactory
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17h3ge2vqnqkeemusg3zhmaxq5m0ttf6jkyjeam4a2vnxaaxq4das5wynws
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyZERWWUJuZFFhZnpZUGpj
            eVRVc2pSUXJ3SGVCWHpVWnF1aGYyUFc4VGw4Cm4yT1Z1cW5lZ3c5NS9kK01abjN6
            eUwyWm1CaGtZU21VSUx0dUFXdmV3SjgKLS0tIGpBOHZmMkI3RW1xc1N1ZmlyeUsx
            WlV5Yk1XcFBKbWJDeW5tdWlKYVBWVUkKanSYGFxGm42iSXwrWO6PvkMhiulGe847
            OmihP9ZrUPkHCfgllhHI+si2FCmhpiTvZx8DDDARZoZ+y0rW5GRj0A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-03T00:22:36Z"
    mac: ENC[AES256_GCM,data:ORwf0a15ri8sCQ9p9nIBjQMGEJa5wVh534oivKlfXTmd8tgZOj690UzziYGZn7Xwxm8ssTJ6VGFxNuPLcN7m8CVga9d95rJtvaF18K5423OxPiwzDZQo32xCBK3v0llcGIzUyKAyiwOCNZ95UTCNEZWqfiSnoZzHT7FuEHSLztY=,iv:FsEfdGhu6b1gOMszTAul5SdgEIESX7JZ7LA72e+FQuk=,tag:cW2AUT8FJNLWA25l8T+jbQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
