apiVersion: v1
kind: Pod
metadata:
  labels:
    run: curler
  name: curler
  namespace: seldon
spec:
  containers:
    - name: curler
      image: fedora:29
      tty: true
  serviceAccount: seldon-deploy
  serviceAccountName: seldon-deploy