apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: greeter
  namespace: seldon
spec:
  template:
    metadata:
      labels:
        maistra.io/expose-route: "true"
    spec:
      containers:
        - image: quay.io/rhdevelopers/knative-tutorial-greeter:quarkus
          livenessProbe:
            httpGet:
              path: /healthz
          readinessProbe:
            httpGet:
              path: /healthz
          resources:
            limits:
              cpu: "0.8"
              memory: 200M
            requests:
              cpu: 200m
              memory: 100M