apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: message-dumper
  namespace: seldon
spec:
  template:
    metadata:
      labels:
        maistra.io/expose-route: "true"
      annotations:
        autoscaling.knative.dev/minScale: "1"
    spec:
      containers:
        - image: gcr.io/knative-releases/github.com/knative/eventing-sources/cmd/event_display
          resources:
            limits:
              cpu: "0.8"
              memory: 200M
            requests:
              cpu: 200m
              memory: 100M