apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-base
  namespace: argocd
spec:
  destination:
    namespace: istio-system
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
      - values.yaml
    path: ../../../base/service-mesh/istio-base
    repoURL:  https://github.com/asongent/stack.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

--- 
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingressgateway
  namespace: argocd
spec:
  destination:
    namespace: istio-system
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
      - values.yaml
    path: ../../../base/service-mesh/ingressgateway
    # kustomize:
    #   version: v4.5.7
    repoURL:  https://github.com/asongent/stack.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
--- 
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istiod
  namespace: argocd
spec:
  destination:
    namespace: istio-system
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
      - values.yaml
    path: ../../../base/service-mesh/istiod
    # kustomize:
    #   version: v4.5.7
    repoURL:  https://github.com/asongent/stack.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      