apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jupytherhub
  namespace: argocd
spec:
  destination:
    namespace: jupyterhub
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
      - values.yaml
    path: jupyterhub
    repoURL:  https://github.com/asongent/stack.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true