apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: matrics-server
  namespace: argocd
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
      - values.yaml
    path: ../../../base/metrics-server
    # kustomize:
    #   version: v4.5.7
    repoURL:  https://github.com/asongent/stack.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true