apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
      - values.yaml
    path: ../../../base/monitoring/prometheus
    repoURL:  https://github.com/asongent/stack.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

# ##This is Optional. You can pull directly remotely if you don't want
# ##to pull prometheus helm chat and save it locally
# --- 
# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: prometheus
#   namespace: argocd
# spec:
#   destination:
#     server: https://kubernetes.default.svc
#     namespace: monitoring
#   project: default
#   source:
#     chart: prometheus
#     helm:
#       values: |
#         pushgateway:
#           enabled: false
#     repoURL: https://prometheus-community.github.io/helm-charts
#     targetRevision: 15.12.0
#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true