apiVersion: eventing.knative.dev/v1alpha1
kind: Trigger
metadata:
  name: message-dumper-trigger
  namespace: seldon
spec:
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: message-dumper